FIX: Fixed issue where a crash could occur when an error page is generated by the CMS
silverstripe/silverstripe-errorpage pull request #59
Opened 2021-05-07 20:04 UTC by UndefinedOffset

This pull request fixes an issue where an `InvalidArgumentException` will be thrown if the `PageController::init()` method defines requirements in the theme for the site and an error page is generated in the cms such as a page not found or server error. This is caused by `LeftAndMain` setting the theme mix to it's config setting `admin_themes`.

This affects all versions of Silverstripe that have been using the `admin_themes` config option to change SSViewer's themes. That said I've verified this issue is present in 4.7.3 and 4.6.1, I would assume it's also present in 4.8.

The one potential downside (though it may not be a bad thing) is that the theme's error page template is used as would be expected outside of the cms.

2021-05-07 20:04 UTC, UndefinedOffset commented
I've targeted 1.6 as it's the lowest supported version :)

2022-01-26 22:01 UTC, emteknetnz requested changes
Sorry based on the description I'm finding this very confusing.  Can you please provide replication steps so that I can test this before and after

2022-01-27 13:47 UTC, UndefinedOffset commented
1. In your `PageController` load any requirement from the site's theme using `SilverStripe\View\Requirements` (css or js)
2. Log into the cms and go to something that would 404 such as `admin/page-not-found` for example
3. This should produce an error `[Emergency] Uncaught InvalidArgumentException: The css file doesn't exist. Please check if the file path/to/file.css exists in any context or search for themedCSS references calling this file in your templates.`

This happens because `SilverStripe\ErrorPage\ErrorPageController` extends `PageController` and the CMS changes the theme mix by default to `silverstripe/admin:cms-forms` and `SSViewer::DEFAULT_THEME` which do not have the file requirements is trying to load. Hopefully that helps @emteknetnz.

Also confirming this is happening in SiteConfig 4.10.0 with Silverstripe 4.10.0 as well.

2022-01-27 21:46 UTC, emteknetnz commented
I wasn't able to replicate this when I was trying earlier.  I tried this with a single theme 'simple', which it seemed like was resolved via SSViewer::DEFAULT_THEME / '$default'

Could you let me know your theme setup and the exact path you're using in `Requirements::css()` ?

2022-01-27 21:54 UTC, UndefinedOffset commented
So from mysite's yaml config:

```yml
---
Name: app
---
SilverStripe\View\SSViewer:
  themes:
    - '$public'
    - 'sitesthemename'
    - '$default'
```

For in `PageController::init()` it loads `Requirements::themedCSS('javascript/externals/floatl/floatl.min.css');`. Without this pull request hitting `admin/page-not-found` results in:

```
[Emergency] Uncaught InvalidArgumentException: The css file doesn't exist. Please check if the file javascript/externals/floatl/floatl.min.css.css exists in any context or search for themedCSS references calling this file in your templates.
```

If I dump out what themes `ThemedResourceLoader` tried to use it returns a result of the below which makes sense given the 404 is coming from `LeftAndMain`.
```
array(2) {
  [0]=>
  string(28) "silverstripe/admin:cms-forms"
  [1]=>
  string(8) "$default"
}
```

2022-01-31 02:34 UTC, emteknetnz commented
Sorry, I still cannot replicate this despite using `Requirements::themedCSS()` and 2 different custom themes.  It makes no difference if the page type is `Page` or `ErrorPage`

Dumping out `SSViewer::config()->themes` in ErrorPage::init() shows my 4 themes e.g.
```
SilverStripe\View\SSViewer:
  themes:
    - '$public'
    - 'simple'
    - 'testtheme'
    - '$default'
```

I can delete the existing error pages and run dev/build flush=1 in CLI, directly access the error pages, and create new error pages using the CMS

Is there a specific series of steps that need to be followed to trigger this error?

2022-01-31 23:13 UTC, emteknetnz requested changes
OK thanks for clarifying replication instructions, I was able to replicate

I've added a suggested docblock comment to add to explain why we are doing this

2022-01-31 23:13 UTC, emteknetnz commented on src/ErrorPageController.php
> +
```suggestion
```

2022-01-31 23:13 UTC, emteknetnz commented on src/ErrorPageController.php
> +    protected function init()
```suggestion
    /**
     * Explicitly set themes to the themes config value in case the theme was previously set to something else
     * One example of this is when serving 404 error pages under the admin path e.g. admin/non-existent
     * where LeftAndMain::init() will have previously set themes to the admin_themes config
     */
    protected function init()
```

2022-02-01 13:47 UTC, UndefinedOffset commented on src/ErrorPageController.php
> +
Removed :)

2022-02-01 13:47 UTC, UndefinedOffset commented on src/ErrorPageController.php
> +    protected function init()
Added :)

2022-02-01 13:47 UTC, UndefinedOffset commented
I've added the suggested edits

2022-02-01 20:31 UTC, emteknetnz approved these changes

2022-02-01 20:32 UTC, merged