ENH add config for allowed_error_codes
silverstripe/silverstripe-errorpage pull request #91
Opened 2023-09-25 03:47 UTC by andrewandante

Fixes #90 

Allows configuration of error codes for the dropdown via `allowed_error_codes` config var.

2023-09-25 21:50 UTC, GuySartorelli requested changes
Thanks for this! Some requested changes below.

2023-09-25 21:50 UTC, ChloeSartorelli commented on README.md
> +```
Can you please also make a PR for the developer-docs repository and add this to the changelog?

2023-09-25 21:50 UTC, GuySartorelli commented on src/ErrorPage.php
> +    private static $db = [
In the future, please keep changes like this in a separate commit, if not a separate PR entirely. It increases the effort to review if these unrelated changes are mixed in.
You can leave them as-is for this PR, just a note for the future.

2023-09-25 21:50 UTC, GuySartorelli commented on src/ErrorPage.php
> +    private static $allowed_error_codes = null;
```suggestion
     * If null, defaults to all available codes (see self::getCodes())
     */
    private static ?array $allowed_error_codes = null;
```
- `@config` is implied, so it's not needed here.
- We prefer to explicitly typehint new properties, even config properties, instead of using phpdoc. The typehint itself isn't enforced by the config system but could be in a future release.

2023-09-25 21:50 UTC, GuySartorelli commented on src/ErrorPage.php
> +        $allowedCodes = self::config()->get('allowed_error_codes');
```suggestion
        $allowedCodes = static::config()->get('allowed_error_codes');
```
Preferably only use `self` if we're using uninherited config. In this case someone could have some crazy use case where they want a sublclass of `ErrorPage` to have different allowed codes, so using `static` enables that use case.

2023-09-25 21:50 UTC, ChloeSartorelli commented on tests/ErrorPageTest.php
> +        Config::modify()->set(ErrorPage::class, 'allowed_error_codes', null);
```suggestion
```
Config should be resetting after each test, so we shouldn't need this.

2023-09-25 21:50 UTC, ChloeSartorelli commented on tests/Fake/FakeErrorPage.php
Please delete this class and use either reflection or `getCMSFields()` and fetch the list from the form field instead.

2023-09-25 21:50 UTC, ChloeSartorelli commented on tests/ErrorPageTest.yml
> +
```suggestion
```
With that class removed, we can either use one of the pre-existing fixtures, or even just get a `new ErrorPage()` since it uses no data from the database.

2023-09-25 22:20 UTC, andrewandante commented on src/ErrorPage.php
> +    private static $allowed_error_codes = null;
Ah ok, so I should treat changes like a self-contained piece of work that adheres to best practices, rather than trying to keep it consistent with the existing file. Got it 😉 will keep that in mind for future PRs

2023-09-25 22:38 UTC, GuySartorelli commented on tests/ErrorPageTest.php
> +        $allCodes = $page->getCMSFields()->fieldByName('ErrorCode')->getSource();
CI is unhappy - probably need to use `dataFieldByName` here.

2023-09-25 22:42 UTC, andrewandante commented on README.md
> +```
Sure thing! At the 5.2.0 changelog, or 5.1.0?

2023-09-25 22:44 UTC, GuySartorelli commented on README.md
> +```
5.2.0 please 💙

2023-09-26 23:48 UTC, GuySartorelli approved these changes
This is great! Works exactly as expected. Thank you.

2023-09-26 23:48 UTC, merged